name: build

on:
  push:
    paths-ignore:
      - '**.md'
    branches-ignore:
      - "gh-pages"
  pull_request:
    paths-ignore:
      - '**.md'
    branches-ignore:
      - "gh-pages"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        java:
          - graalvm@
          - zulu@
          - zulu@1.8
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
      fail-fast: false
    steps:
      - name: Configure git
        run: "git config --global core.autocrlf false"
        shell: bash
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
      - uses: coursier/cache-action@v5
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{matrix.java}}
      - name: Compile, test and check binary compatibility
        run: "sbt -batch clean +test +mimaReportBinaryIssues"
        shell: bash
